// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsqtuudvjshunvncyfen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcXR1dWR2anNodW52bmN5ZmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODQyOTQsImV4cCI6MjA3MjY2MDI5NH0.xCFZLet54S7-vjQzeIYGNc-Cn74I2y_7ybINU9GJi4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});